# Generated by Django 3.2.15 on 2022-08-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devlints', '0002_company_eula_gdprcompliance_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='twitter',
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
